@startuml koderush-joinMatch

User -> API : joinMatch(matchId, playerName)
API -> joinMatchLambda : trigger(matchId, playerName, connectionId)
joinMatchLambda -> tempPlayersMatchId : insert(playerName, connectionId)
joinMatchLambda -> tempPlayersMatchId : getConnectionIds()
tempPlayersMatchId -> joinMatchLambda : Connection Ids
joinMatchLambda -> API : newPlayer(Connection Ids)
API -> Players : newPlayer
joinMatchLambda -> API : stateUpdate(Connection Ids)
API -> Players : stateUpdate

@enduml